/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEWorldCupVoteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canSubmit"
      | "grantSelfAccessAgain"
      | "isRegistered"
      | "protocolId"
      | "readEncryptedGuess"
      | "recordEncryptedGuess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "canSubmit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantSelfAccessAgain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readEncryptedGuess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordEncryptedGuess",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "canSubmit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantSelfAccessAgain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "readEncryptedGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordEncryptedGuess",
    data: BytesLike
  ): Result;
}

export interface FHEWorldCupVote extends BaseContract {
  connect(runner?: ContractRunner | null): FHEWorldCupVote;
  waitForDeployment(): Promise<this>;

  interface: FHEWorldCupVoteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canSubmit: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  grantSelfAccessAgain: TypedContractMethod<[], [void], "nonpayable">;

  isRegistered: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  readEncryptedGuess: TypedContractMethod<
    [wallet: AddressLike],
    [string],
    "view"
  >;

  recordEncryptedGuess: TypedContractMethod<
    [encryptedInput: BytesLike, validationProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canSubmit"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "grantSelfAccessAgain"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "readEncryptedGuess"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "recordEncryptedGuess"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, validationProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
